 groups:
  - name: container_cpu_usage
    rules:
      - alert: HighContainerCPUUsage
        expr: (rate(container_cpu_usage_seconds_total{name=~".+"}[1m])) * 100 > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage on container {{ $labels.name }}"
          description: "Container {{ $labels.name }} is using more than 80% CPU."





#
# groups:
# - name: Example
#   rules:
#
#     - alert: InstanceDown
#       expr: up == 0
#       for: 2m
#       labels:
#         severity: critical
#       annotations:
#         summary: "Instance [{{ $labels.instance }}] down"
#         description: "[{{ $labels.instance }}] of job {{ $labels.job }} has been down for more than 2 minutes."
#
# # - name: NodeMemUsgae
#   # rules:
#     - alert: HostMemoryIsUnderutilized
#       expr: ({__name__="node_memory_MemAvailable_bytes", instance="node-exporter:9100", job="node"} > 80)
#       for: 15s
#       labels:
#         severity: critical
#       annotations:
#         summary: Host Memory is underutilized (instance {{ $labels.instance }})
#         description: "Node memory is < 20% for 1 week. Consider reducing memory space. (instance {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
